// Fichas inventadas para evaluar los menús de la IA. No son personas reales.
// Se pueden editar o agregar más: cada ficha usa los mismos campos que la ficha de la app.
const medicion = (weight, height) => [{ id: "m1", date: "2026-01-10", weight, height, createdAt: 1 }];

export const FICHAS_EJEMPLO = [
  { id: "ej-general-trabajo", name: "Ejemplo general, trabaja", age: 35, condition: "general", goal: "Ordenar horarios y comer más variado", likes: "milanesa, pastas", avoids: "", allergies: "", budget: "economico", schedule: "Trabaja de 8 a 17", lunchPlace: "work_basic", cookingTime: "poco", kitchen: ["microwave"], context: "Almuerza en el trabajo.", equationSex: "female", activityLevel: "light", measurements: medicion(68, 164) },
  { id: "ej-diabetes-casa", name: "Ejemplo diabetes tipo 2", age: 58, condition: "diabetes2", goal: "Mejorar el control de la glucemia", likes: "carne al horno, guiso de lentejas", avoids: "", allergies: "", budget: "medio", schedule: "Está en su casa todo el día", lunchPlace: "home", cookingTime: "medio", kitchen: ["oven", "microwave"], context: "", equationSex: "male", activityLevel: "sedentary", measurements: medicion(84, 172) },
  { id: "ej-hipertension", name: "Ejemplo hipertensión", age: 62, condition: "hipertension", goal: "Reducir la sal y bajar de peso", likes: "pollo, verduras", avoids: "fiambres", allergies: "", budget: "economico", schedule: "Jubilada", lunchPlace: "home", cookingTime: "mucho", kitchen: ["oven"], context: "", equationSex: "female", activityLevel: "light", measurements: medicion(76, 158) },
  { id: "ej-ambas-afuera", name: "Ejemplo diabetes e hipertensión, come afuera", age: 50, condition: "ambas", goal: "Control general", likes: "", avoids: "", allergies: "", budget: "economico", schedule: "Camionero, come en rutas", lunchPlace: "outside", cookingTime: "poco", kitchen: [], context: "Almuerza en comedores de ruta.", equationSex: "male", activityLevel: "moderate", measurements: medicion(92, 175) },
  { id: "ej-alergias", name: "Ejemplo con alergias", age: 27, condition: "general", goal: "Ganar masa muscular", likes: "arroz, pollo, banana", avoids: "cerdo", allergies: "maní, huevo", budget: "medio", schedule: "Estudia y entrena a la tarde", lunchPlace: "home", cookingTime: "medio", kitchen: ["oven", "microwave", "airfryer"], context: "", equationSex: "male", activityLevel: "high", measurements: medicion(66, 178) }
];
